server:
  port: 8080

spring:
  cloud:
    stream:
      bindings:
        input-channel-1:
          destination: pos-topic
      kafka:
        streams:
          binder:
            applicationId: streamexactonce
            brokers:  localhost:9092
            bindings:
              input-channel-1:
                consumer:
                  valueSerde: org.springframework.kafka.support.serializer.JsonSerde
            configuration:
              commit.interval.ms: 10000
              state.dir: state-store-streamonce